In [1]:
import pandas as pd
stocks = pd.read_csv(r'data/stocks_cleaned.csv')
stocks

    ticker                  name
0     NVAX               Novavax
1     SIRI             Sirius XM
2      QQQ           Invesco QQQ
3     AAPL                 Apple
4     MSFT             Microsoft
..     ...                   ...
578    XYL                 Xylem
579    YUM           YUM! Brands
580    ZBH         Zimmer Biomet
581   ZION  Zions Bancorporation
582    ZTS                Zoetis

[583 rows x 2 columns]

In [5]:
import pandas as pd
from pathlib import Path
import os
df = pd.read_pickle(r"data/stocktwits_raw_full.pkl")
df

,id,text,time,sentiment
0,411896118,$BABA I’m comfortable at $127.50. I’ll check b...,1638291431,Bullish
1,411895020,$BABA how low does this POS go tomorrow is the...,1638291222,
2,411894156,@Nobrainer6868 $BABA started my first 5% posit...,1638291057,
3,411894124,$BABA You guys want me to sell down here? Look...,1638291050,
4,411893846,$BABA at this price point shorts are better of...,1638291000,
...,...,...,...,...
445639,420617596,Short sale volume (not short interest) for $US...,1640478214,
445640,420610698,SweepCast observed: $USB with Unusual Options ...,1640466364,
445641,420573882,"HSBC To Buy L&amp;T Investment, Boosts Wealth ...",1640437216,
445642,420437859,How does this affect your portfolio? $USB&#39;...,1640326224,
445643,420433589,MOVES HAPPENING NOW (8:25am)\n\n⦿ $USB is down...,1640323511,

In [6]:
import re
# given a text, find the related symbols and remove it 
# return: a string of text and a list of symbols
def extract_syb(text):
    symbols = re.findall(r"\B[$][a-zA-Z]*", text)
    symbols = [i for i in symbols if i != "$"]
    if len(symbols) == 1:
        return symbols[0]
    else:
        return None

df['symbols'] = df['text'].apply(extract_syb)
df = df.dropna(subset=['symbols'])
df['symbols'] = [i.upper() for i in df['symbols']]
df

C:\Users\samue\AppData\Local\Temp/ipykernel_11024/2855401207.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['symbols'] = [i.upper() for i in df['symbols']]

,id,text,time,sentiment,symbols
0,411896118,$BABA I’m comfortable at $127.50. I’ll check b...,1638291431,Bullish,$BABA
1,411895020,$BABA how low does this POS go tomorrow is the...,1638291222,,$BABA
2,411894156,@Nobrainer6868 $BABA started my first 5% posit...,1638291057,,$BABA
3,411894124,$BABA You guys want me to sell down here? Look...,1638291050,,$BABA
4,411893846,$BABA at this price point shorts are better of...,1638291000,,$BABA
...,...,...,...,...,...
445638,420618061,USBancorp $USB BidaskScore is #Reiterated to S...,1640479505,,$USB
445639,420617596,Short sale volume (not short interest) for $US...,1640478214,,$USB
445640,420610698,SweepCast observed: $USB with Unusual Options ...,1640466364,,$USB
445642,420437859,How does this affect your portfolio? $USB&#39;...,1640326224,,$USB
445643,420433589,MOVES HAPPENING NOW (8:25am)\n\n⦿ $USB is down...,1640323511,,$USB

In [11]:
not_yet_scrapped = set(stocks.ticker) - set([i[1:] for i in df.symbols])  
for i in not_yet_scrapped:
    print(i, end=' ')

AN IP NUAN ALLE FL PAH CCI EIX VRSK VALE MOMO CRM CAG AET IPG AEE AXP AVGO AWK AMP COG KSS EMR OKE ATVI CMI YNDX KORS ARE MHK SJM CINF TJX INCY NEM SIG COTY RTN CCL MAT KIM CRZO CHTR IMGN STT SRCL AAOI EXR GRMN TXT COST JNPR UNP EW T FIS CERN SPG VIAB DG ILMN VNO OAS QRVO PEP ZBH AKS RCL ARRY MGM M DHI DOV AON PBR VRTX KMX UA RSG VZ KMB PEG APA D ICE MNK SIRI OCLR MNST XLNX SRC PSX COL TIF RHT TMO KSU TXN TWX ADM STI GD ROP KHC FITB BXP MTB SQQQ VAR ETE CBOE ALK CBS RE NWL NSC DISH UAL SYK SLCA HIBB EA TRQ TSCO MAA IRM CTXS JCP RHI DFS EL AZO WU ADS DUK EXPD MPC NKTR WFT MAS DKS SHW PFE GOOG MCK GPC XRX URI MKC FAST NTRS JCI FTI SNPS HSIC GPS F SWKS O CAT AGNC ALL ENDP CLF ETN PDCO EVHC PSA BZUN GE SEE STX BAX UNM MCO AIV XEL HES MU SNA HDS MCD BIDU TRIP FMC PXD NTNX CXO GG RL JWN ETR GNTX BSX LKQ DTE ABT WPX FEYE CHRW CMS WBA PAYX LNC SCG ORLY ROK DLR KEY APC ZNGA LYB MMC IBM UHS TVIX MTD APH MRO COF PHM CFG AES PVH PNR HLT BMY KGC ABBV ECL NFX PPG VRX RRC DAL PCAR ZTS CSX AFL KLAC SQ NDAQ MMM AMTD ESS PLD SVU NOC FMSA X AYI FTV IBN FRT HOLX L HBI PCG REG DLPH FFIV MON TEL ACN CTL DRI GWW SRE DISCA CSCO DGX ZION CHD FDX TLT LEG MET HPQ CPB IR LLY NAVI LRCX MDLZ EQT INFO AMG SLB UAA DXC APD DE EFX PNW VMC ADP CVS BA TMUS DHR PG FE ADI BBT ISRG LLL LEN CTAS ANSS SO S STZ ADBE TQQQ GLUU WRK PH BK UDR AEP WYN TAP LMT CME HRB PETS GGP RF TGT LH HPE CMA OMC XL AME CHK CTSH NOK NLSN ES FISV IT HD EMN HCA CL DVN NKE PBCT MUR XYL PM BWA WYNN FNSR TDG SRPT HOG AVY FLR MYL BIIB EQR HTZ AGN TRV VRSN GRPN KR HST ADSK GIS MO IDXX MOS DCIX DVA ESRX YUM NUE SPGI NOV INTU FLIR FOXA EOG CELG ABC WHR PTEN BBY DPS AMD XEC AAP PKI AMGN ON CI DLTR PX ALXN CDNS HRL GILD CNC COP WLTW NLY ROST PWR WAT MCHP PRGO EXEL CMG VTR MDT WY WFC CB NI FOX GT OXY FLEX MRK CVX PNC AUY EXPE HAS HUM A MAR GM TSS RAD JBHT LITE CLX ODP UPS BDX DDR AVB WEC CMCSA AKAM BHGE VIPS EXC NTAP SYMC TROW ULTA DISCK ITUB IVZ SYF TSN REGN RIG SLG LB VLO ETFC IFF HRS FCX PRU GLW FBHS BEN CX ABEV MLM NVAX CNP WLL COO JEC CY RJF HP LUK UTX ESV MAC ALGN PPL LUV SWK EQIX AIG ARNC APRN NBL PFG SCHW K SGMS ABX SNAP SAN NRG BLK SLM AJG AMAT ERIC HAL KMI CF CAH MSI ALB BBBY HIG P ED AMT FLS NEE HIMX AIZ SWN WM AAL GNCA TMK ITW ANTM LNT WDC HON SYY HBAN SPN FWONK AABA LOW HCP PGR XRAY VFC WMB HSY JBLU GPN