In [1]:
import pandas as pd
from pathlib import Path
import os

directory = Path(os.getcwd())   # 'c:\\Users\\samue\\OneDrive\\Desktop\\JPM Fintech\\HKUST-x-J.P.-Morgan-Fintech-Mentorship-Program\\model_testing\\supervised'
directory = directory.parent.parent.joinpath("data")  # 'c:\\Users\\samue\\OneDrive\\Desktop\\JPM Fintech\\data'
df = pd.read_pickle(directory.joinpath("stocktwits_processed_cleaned_full.pkl"))
df

,id,text,time,sentiment,symbols,label
0,411896118,I’m comfortable at $127.50. I’ll check back in...,1638291431,Bullish,$BABA,1
1,411895020,how low does this POS go tomorrow is the milli...,1638291222,,$BABA,1
2,411894156,@Nobrainer6868 started my first 5% position t...,1638291057,,$BABA,1
3,411894124,You guys want me to sell down here? Look at th...,1638291050,,$BABA,1
4,411893846,at this price point shorts are better off flip...,1638291000,,$BABA,1
...,...,...,...,...,...,...
386925,420650655,Representative Peter Welch Sold Shares of on ...,1640513683,,$USB,1
386927,420617596,Short sale volume (not short interest) for on...,1640478214,,$USB,1
386928,420610698,SweepCast observed: with Unusual Options Acti...,1640466364,,$USB,1
386929,420437859,How does this affect your portfolio? 's in Upt...,1640326224,,$USB,1
386930,420433589,MOVES HAPPENING NOW (8:25am) ⦿ is down 0.0% ...,1640323511,,$USB,1

In [2]:
df=df[df['sentiment']!='']

In [3]:
df

,id,text,time,sentiment,symbols,label
0,411896118,I’m comfortable at $127.50. I’ll check back in...,1638291431,Bullish,$BABA,1
8,411891279,@tesla_S is this protected from nationalism th...,1638290493,Bearish,$BABA,1
17,411888215,"Which one is faster. Losing a boner, or gettin...",1638289900,Bullish,$BABA,1
20,411886038,this is about to pump HARD lets fuckin do this...,1638289479,Bullish,$BABA,1
22,411883938,below 100 coming soon Two digits 80s next stop...,1638289076,Bearish,$BABA,1
...,...,...,...,...,...,...
386775,414993587,Twits Stats Today's Change 18% + 🚀,1638953112,Bullish,$USB,1
386793,414266558,just buy and hold past 700 shares.,1638795474,Bullish,$USB,1
386796,413911285,Twits Stats Today's Change 18% + 🚀,1638721922,Bullish,$USB,1
386801,412309963,Twits Stats Today's Change 18% + 🚀,1638361338,Bullish,$USB,1
386912,423398417,Banks are the way in 2022. I bet on it!,1641300772,Bullish,$USB,1

In [4]:
def bull_bear(text):
    #print(text)
    return 0 if text == "Bullish" else 1 

df=df[['text', 'sentiment']]

In [5]:
df['sentiment'] = df['sentiment'].apply(bull_bear)
df

C:\Users\samue\AppData\Local\Temp/ipykernel_33896/889624449.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment'] = df['sentiment'].apply(bull_bear)

                                                     text  sentiment
0       I’m comfortable at $127.50. I’ll check back in...          0
8       @tesla_S is this protected from nationalism th...          1
17      Which one is faster. Losing a boner, or gettin...          0
20      this is about to pump HARD lets fuckin do this...          0
22      below 100 coming soon Two digits 80s next stop...          1
...                                                   ...        ...
386775                 Twits Stats Today's Change 18% + 🚀          0
386793                 just buy and hold past 700 shares.          0
386796                 Twits Stats Today's Change 18% + 🚀          0
386801                 Twits Stats Today's Change 18% + 🚀          0
386912            Banks are the way in 2022. I bet on it!          0

[87148 rows x 2 columns]

In [9]:
df.sample(20)

                                                     text  label
371783    QQQ double bottom of Tuesday should bounce here      0
65020                                    ONCE OVER $170!!      0
169365                            take that to the bank 🏦      0
329211  7.2 MILLION AFTER HOURS ALREADY!!! SANTA COMIN...      0
115094  All I want for this Christmas is “Amazon Split...      0
241154  I have to say...@TRADINGGODS_ has been on poin...      1
97948                      Another dip for you dip buyers      0
281292                              going to 2k in 2022!?      0
183942                                     brick wall @46      0
7625    2x average 200 sma and everyone is selling say...      0
364857  One of the few charts that held it together th...      0
122835  jasmy is hardly been effected compared to btc ...      0
60497   who’s ready? $308 today most likely. close ove...      0
324586       2% Correction and everyone loses their minds      1
13218   lmaoo where’s the guy that should we would nev...      0
19146   However, sooner or later, the top two influenc...      1
208364                          we see $60K EOY??? LFG!!!      0
358541  A man who smuggled copies of smash hit South K...      1
224279  wonder if cathie will buy back when the 30 day...      0
51911   - Came into session looking to buy. Price move...      1

In [6]:
df = df.rename(columns={'sentiment': 'label'})

In [7]:
train=df.sample(frac=0.7,random_state=200) #random state is a seed value
test=df.drop(train.index)

In [8]:
#train.to_csv("dataset/train.csv", index=False)
#test.to_csv("dataset/test.csv", index=False)